version: '3.8'

services:
  bruxism-bot-backend:
    build: .
    container_name: bbot_backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DB_HOST=bruxism-db-chatbot-bruxism.l.aivencloud.com
      - DB_PORT=14920
      - DB_USER=avnadmin
      - DB_PASS=AVNS_cE7bUYJayOMigFfkP-t
      - DB_NAME=defaultdb
      - DB_DIALECT=mysql
      - JWT_SECRET=chatbot-secret
      - TELEGRAM_BOT_TOKEN=8723295703:AAHkGaLxl0EUyUIk_d11lw-MCo88uD4kGOk
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"